services:
  agents-pilldispenser:
    image: docker.telepat.online/agents-pilldispenser-image:latest
    container_name: pill-dispenser-agent
    env_file:
      - .env
      - enviroments/pilldispenser.env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false
      - HOST="${PROTOCOL}://pills.${AGENT_DOMAIN}"
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_PORT=80
    entrypoint: |
      /bin/sh -c '
        goose postgres "$(manage -c print-db-string)" -dir=internal/db/migrations up
        server
      '
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agents-net
    labels:
      - dev.dozzle.group=agents-pilldispenser
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - "80"
