services:
  server:
    container_name: pill-dispenser-agent
    image: pill-dispenser-bot
    restart: always
    build:
      context: .
      target: dev
    ports:
      - "3054:3054"
    volumes:
      - ./:/src
