services:
  server:
    container_name: pill-dispenser-agent
    build:
      context: .
      target: dev
    ports:
      - "3054:3054"
    volumes:
      - ./:/src
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
