services:
  server:
    container_name: pill-dispenser-agent
    restart: always
    build:
      context: .
      target: prod
    ports:
      - "3054:3054"
    command: server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - db-data:/tmp/sqlite-db
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}

volumes:
  db-data:
    name: "pill-dispenser-db-data"
