services:
  server:
    container_name: pill-dispenser-agent
    image: docker.telepat.online/agents-pilldispenser-image:latest
    network_mode: "host"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
