services:
  server:
    container_name: pill-dispenser-agent
    image: pill-dispenser-bot
    restart: always
    build:
      context: .
      target: dev
    ports:
      - "3054:3054"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - db-data:/tmp/sqlite-db
      - ./:/src

volumes:
  db-data:
    name: "pilldispenser-db-data"
