services:
  server:
    container_name: pill-dispenser-agent
    image: docker.telepat.online/agents-pilldispenser-image:latest
    restart: unless-stopped
    entrypoint: |
      /bin/sh -c '
        goose postgres "$(manage -c print-db-string)" -dir=internal/db/migrations up
        server
      '
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      - SOURCE_COMMIT=${SOURCE_COMMIT}
      - DEBUG=false
